[
  "Radius",
  "Single Target",
  "Caster",
  "Special",
  "Line",
  "One Corpse",
  "One Object",
  "One Creature",
  "Two Creatures",
  "One Metal Block",
  "One Door",
  "One Tree",
  "One Rope",
  "One Lump Of Clay",
  "One Weapon",
  "One Armor",
  "One Block Of Clay",
  "One Stone",
  "One Boulder",
  "One Ship",
  "Two Targets",
  "One Fire",
  "One Space",
  "One Book",
  "One Lock"
]