[
  "Enchantment Spell",
  "Spell Attack",
  "Summoning Spell",
  "Area Spell Attack",
  "Spell",
  "Ranged Spell Attack",
  "Cloud Spell",
  "Ritual Spell",
  "Wall Spell",
  "Area Spell",
  "Teleport Spell",
  "Mind Spell Attack",
  "Touch Spell Teleport Attack",
  "Ritual Teleport Spell",
  "Transformation Spell",
  "Body Spell Attack",
  "Ground Spell",
  "Touch Spell Attack",
  "Portal Spell",
  "Reflex Spell Attack",
  "Divination Spell",
  "Cloud Enchantment Spell",
  "1 Week",
  "Transmutation Spell",
  "Illusion Spell",
  "Phantasm Spell",
  "Ground Enchantment Spell",
  "Spell Body Attack"
]